### PR TITLE
fix: On select select the first result

### PR DESCRIPTION
**Pull request by ChFlick**

### CODE REVIEW

**Comment by dubisdev** [comment]
Hi @ChFlick do you have npm account?

As I can't configure the secret here, I think the best option will be to add you to the npm org so you can publish when you ship new stuff.

**Comment by ChFlick** [comment]
Yeah sure thats fine. That's my npm account -> https://www.npmjs.com/~chflick

**Comment by ChFlick** [comment]
Yeah sure we can do it like that. That's my npm account -> https://www.npmjs.com/~chflick

**Comment by dubisdev** [comment]
I just sent you an invitation 🤝

**Pull request merged**
